### ISSUE TITLE
Windows Module not found

### ISSUE THREAD

**Issue by PhilippeduPreez** [flowershow/flowershow#152]
Currently getting a module not found error in Windows

![Capture](https://user-images.githubusercontent.com/44789132/188806185-33d5796a-81f5-418c-96c7-f1bd6beed7a0.PNG)

**Comment by olayway** [comment]
@PhilippeduPreez I've quickly checked it on Windows. When you clone the repo on Windows the symlink from `templates/default/content` to `site/content` is invalid and is being downloaded as a text file (you can check it in your code editor, that this file contains a string with a path, it's not a symlinked folder) - this is probably due to the fact that paths in Windows are written with backslashes `\`, but on Linux with forward slashes `/`.  Anyways, you just need to remove this file and create a symlink instead.

**Comment by olayway** [comment]
The same goes for `templates/default/components/custom`. It's a file instead of a symlink. You need to remove this file and create a symlink to `site/components`.
There are still a lot of errors though..

**Comment by olayway** [comment]
There is a 3rd place (and the last one 😀) where you need to do do this: `templates/default/public/assets` should point to `site/content/assets`.

**Comment by olayway** [comment]
Actually, this has nothing to do with forward or back slashes. It's just the difference between implementation of symlinks on these two systems.
