### ISSUE TITLE
PDF embedding

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#194]
## Acceptance
- [ ] support for embedding PDF files using transclusion syntax

**Comment by olayway** [comment]
@rufuspollock yes, it works, not sure why but when I tested it it didn't work

**Comment by saviorand** [comment]
@olayway @rufuspollock  doesn't seem to work for me , maybe I'm doing something wrong? Instead of a PDF embed it shows an iframe of the website itself with a 404 page. 

This is the [web page](https://www.valentin.wiki/research/LMF%20Resilience%20in%20COVID), tried both with a file path and a link using the syntax described [here](https://flowershow.app/docs/syntax#pdf-embedding)

**Comment by rufuspollock** [comment]
@saviorand can you paste the snippet or markdown you are using for the embed ... the 404 indicates it is not finding the url for the doc (have you symlinked your assets folder ...?)

**Comment by saviorand** [comment]
@rufuspollock arghh! I haven't symlinked, of course! it works now, thanks 😄
