### ISSUE TITLE
E2E: upload artifacts of running tests

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#211]
Don't remove temporary directories created for each test when the tests are running in the GitHub workflow. Instead, upload them as artifacts to be able to see why some tests may have failed.

https://github.com/actions/upload-artifact

To test whether the tests are running in a GH workflow, check if one of the default env vars is set to some specific value, e.g. CI is set to true, and remove or don't remove the temp directories based on that.

https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables

**Comment by rufuspollock** [comment]
@olayway my 2c is that this would be better addressed by logging output from the test connected (and, if possible, limiting that logging to if test fails).

Generally this is missing a bit of so that - i'm therefore not sure how significant this is. My plan would be to close as WONTFIX for now and reopen if something substantive.

**Comment by rufuspollock** [comment]
WONTFIX. See previous comment.
