### ISSUE TITLE
Feature section v0.2 on the front page

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#247]
When looking at product I want to get an overview of top features at a glance (and be a bit wowed by elegance of presentation)

When looking at product i want to get a sense of the breadth and comprehensiveness of the features

When maintaining the site (as flowershow team member) I don't want to have to keep manually updating feature info in two places e.g. the feature page and the front page features section **Note this is secondary - manually copying for now is not a big deal**

### Details

2 main issues

- We have to manually update info on front page and feature page and these get out of date
- Current feature section is quite plain and not so elegant (see screenshot) => can take inspiration from contentlayer.dev and tailwindui examples
  - stretches across whole page
  - no images

![image](https://user-images.githubusercontent.com/180658/199665463-4e8dd257-a09e-414e-9752-f1694177aac1.png)

## Acceptance

- [x] More elegant features section on front page **Done 2023/03/01**

**Comment by olayway** [comment]
@PhilippeduPreez what's the progress here? Have you found some prettier examples than the one from tailwind ui? If not, I think we could give it a go. It will be much better than what we have now anyway. And once we create a React component and use it instead of the plain MD we can adjust the looks of it in the future :)

**Comment by olayway** [comment]
@PhilippeduPreez how are you getting on with this? Need any help? 🙂
