### ISSUE TITLE
Search component breaks on Next v13.1.6

### ISSUE THREAD

**Issue by khalilcodes** [flowershow/flowershow#419]
After doing a local test upgrade for next to latest version (13.1.6) the site throws the following error in Nav.

<img width="945" alt="Screen Shot 2023-02-06 at 4 30 10 PM" src="https://user-images.githubusercontent.com/42637597/216984390-782b87f1-6d0d-4d92-83bf-cb68aac7e640.png">

Upon further investigation it was found that the Search component is the underlying issue.

Browsing through pliny's code (which is where this was ported from), he has disabled this feature entirely maybe due to similar errors (and looks like he is not going to maintain that feat anytime soon).

## Acceptance

- [ ] Search works on next v13.1.6

## Tasks

- [ ] Refactor search component / fix errors

**Comment by olayway** [comment]
@khalilcodes I'm not sure if it's a matter of Next.js version, because I saw it also while working on next.datopian.com. I knew that the site builds correctly on Cloudflare but I was getting this error when running a dev server locally, so I had to comment out the SearchProvider in the Layout to be able to work on other things 😅 Next time it shows up I'll let you know what versions of Node and Next.js I'm using.

**Comment by rufuspollock** [comment]
@olayway i've also had this locally.

**Comment by olayway** [comment]
@rufuspollock can you also let us know which node version and OS you're using? And when exactly did this error show up? Were you able to run the project previously without the error?

**Comment by khalilcodes** [comment]
@olayway updates: 

updated all deps with some changes in component, and works on node 16 & 18.

blocked by mermaid which throws errors.
